import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Providers from './components/Providers'
import Navbar from './components/Navbar'
import './globals.css'
import '@mantine/core/styles.css';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Trivia Game',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
          <Providers>
            <Navbar />
            {children}
          </Providers>
      </body>
    </html>
  )
}
